### ISSUE TITLE
Slight flickering on 'Dataset for Stereo EVIO' dataset?

### ISSUE THREAD

**Issue by gyubeomim** [arclab-hku/Event_based_VO-VIO-SLAM#12]
Hello Authors,

I'm grateful for the opportunity to use your event-based project and dataset! While testing the 'Dataset for Stereo EVIO,' I noticed a slight flicker effect in the 'HKU aggressive small flip' and 'HKU aggressive walk' recordings when playing the bag files with the following options:

`rosbag play hku_aggressive_small_flip.bag -s8 -r0.05`
`rosbag play hku_aggressive_small_flip.bag -s36 -r0.05`
`rosbag play hku_aggressive_walk.bag -s8 -r0.05`
`rosbag play hku_aggressive_walk.bag -s26 -r0.05`

Could this flicker be caused by the VICON system's IR emitter or the room lighting conditions? Or is it simply a natural phenomenon of the DAVIS346?

Thank you in advance!

**Comment by cpymaple** [comment]
Hi, do you mean the below event streams show "flicker"? 
![2024-06-24 13-49-28 的屏幕截图](https://github.com/arclab-hku/Event_based_VO-VIO-SLAM/assets/80804464/96e62aa8-375c-434c-88a4-4a436832ebe9)

1. We use the IR filter to avoid the effect of VICON or other radiation sources. For more details, you can also refer to our "ECMD: An Event-Centric Multisensory Driving Dataset for SLAM" Section III.A.1).
2. We believe that this is related to the optical performance of the event camera and this is a natural phenomenon for DAVIS346.

**Comment by gyubeomim** [comment]
Yes. I've experienced 
1. I also saw a slight flicker-like effect (large (event amount) --> small --> large for short durations (<10ms))
2. A phenomenon in which events do not appear periodically during high-speed flipping. (I was able to notice this phenomenon because I used SAE representation)
3. Above picture effect

I'll check out the paper you mentioned. 

Thank you for the quick reply!
