### ISSUE TITLE
 About the pose GT of the ECMD dataset

### ISSUE THREAD

**Issue by DongHappyyy** [arclab-hku/Event_based_VO-VIO-SLAM#13]
May I ask if it is possible to publicly release the code for pose GT of the ECMD dataset

**Comment by cpymaple** [comment]
> May I ask if it is possible to publicly release the code for pose GT of the ECMD dataset

Hi, https://github.com/arclab-hku/ecmd is the github of our ECMD dataset. And you can download the pose GT of ECMD datasets on the following link: https://arclab-hku.github.io/ecmd/download/
