### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by YoungHaulk** [arclab-hku/Event_based_VO-VIO-SLAM#3]
Thanks for the great work,！
But the dataset is so large that the download can easily fail. 
Is there any other way to download, such as Baidu Netdisk?

**Comment by cpymaple** [comment]
Thanks for your interest. We will update a new link for downloading the datasets as soon as possible.

**Comment by cpymaple** [comment]
> Thanks for the great work,！ But the dataset is so large that the download can easily fail. Is there any other way to download, such as Baidu Netdisk?

Hi, we have already uploaded the new link (Baidu Disk) for our datasets. Hope it can help you.
