### ISSUE TITLE
ESVIO (VIO Only) and PL-EVIO (VIO Only) performance result request

### ISSUE THREAD

**Issue by edward0im** [arclab-hku/Event_based_VO-VIO-SLAM#4]
Hello Arc Lab,

I would like to request the performance results of the HKU dataset using ESVIO (VIO only) and PL-EVIO (VIO only). These results will help clarify the contribution of the event-based feature tracker.

Could you please share the results?

Thank you in advance.

**Comment by cpymaple** [comment]
Hi,  we evaluate our ESVIO (Visual only) on hku_agg_flip and hku_dark_normal sequence. We give the results and videos link as follows: 
1. ESVIO (Visual only): The mean errors are 0.24 (https://b23.tv/0HLPars) and  2.59 (https://b23.tv/42A6sjy) respectively.
2. ESVIO (Event with Visual): The mean errors are 0.14 (https://b23.tv/IRssT0m) and 0.39 (https://b23.tv/IkJUJww) respectively.
3. ESVIO (Event only): The mean errors are 1.23 (https://b23.tv/83Bh4CW) and 0.32 (https://b23.tv/dJa1i49) respectively.

However, we have another research project recently, and we will publish the results of the remaining sequences in the future.

**Comment by edward0im** [comment]
Thank you for your quick reply. I appreciate your support and anticipate our next research project. :-)
