### ISSUE TITLE
Reference frame for VICON

### ISSUE THREAD

**Issue by ghoshsuman** [arclab-hku/Event_based_VO-VIO-SLAM#7]
Hi. In which reference frame are the VICON poses provided in the stereo VIO dataset? Can you provide the transformation between that and the other sensors please?

**Comment by KwanWaiPang** [comment]
Hi~the VICON poses is for evaluation of the odometry, it should be the body frame (common used). while the transformation between the body frame (imu) and the camera frame should be already available in the documments of the dataset.
please read [https://github.com/arclab-hku/Event_based_VO-VIO-SLAM/blob/main/Results_for_comparison.md](Link) carefully, and use the [https://github.com/MichaelGrupp/evo](evo) or other  package for the evaluation of odometry and SLAM.
thank you
