### ISSUE TITLE
Dataset download links are invalid

### ISSUE THREAD

**Issue by 2565583595long** [arclab-hku/Event_based_VO-VIO-SLAM#8]
Thank you for your outstanding work.

The indoor (no ground truth) and outdoor (no ground truth) dataset download links for monocular EVIO are invalid. Could you please update them?

Thank you again.

**Comment by KwanWaiPang** [comment]
Thank you for your interest. We have provided the download link (Baidu Disk) of the related rosbag.

**Comment by 2565583595long** [comment]
Thank you so much! Looking forward to seeing more outstanding work from you.
